#
#  Rhythm Recipe
#
#
# This file defines the Rhythm Recipe class, which represents a specific test
# we want to run. It provides specific convenience methods to set up a recipe,
# import OCEAN files, and run. 
import os
import csv
import sys
import re
import subprocess
from rhythm_logger import RhythmLogger



class Recipe():


    def __init__(self):
        self.rundir = None         #Run directory (within CWD)
        self.full_rundir = None    #Fully-qualified path to run directory
        self.log = RhythmLogger() 
        self.ocn_script = ""
        self.cdslib = None         #cds.lib file
        self.setup_scripts = []    #Scripts that should be sourced before running simulations (i.e. setup.csh)
        self.analysis_tasks = []

    #################
    # Setup Methods #
    #################

    def set_rundir(self,rundir, local_results=True):
        """Sets the directory in which the Recipe will run.
           If this directory does not already exist, it is created."""
        self.rundir = rundir
        self.full_rundir = os.path.join(os.getcwd(),self.rundir)
        os.makedirs(self.full_rundir, exist_ok=True)

        if local_results:
            pass #self.ocn_script = f"resultsDir( \"{self.rundir}\" )" + self.ocn_script
        

    def set_cdslib(self,cdslib):
        """Specifies the cds.lib file to use for this run."""
        self.cdslib = cdslib

    def add_setup_script(self, new_script):
        self.setup_scripts.append(new_script)

    
    #################################
    # Simulation & Analysis Methods #
    #################################

    def load_ocn(self, ocn_file):
        with open(ocn_file, 'r') as read_file:
            ocn_file_text = read_file.read()
        self.ocn_script += ocn_file_text

    
    def save_output(self,output_name,save_method):
        """Instruct rhythm to save a particular output with a particular method."""
        if save_method == "CSV":
            self.ocn_script += f"\nocnPrint( ?output \"{output_name}.txt\" "
            self.ocn_script += f"?numberNotation `engineering {output_name} )"
            self.analysis_tasks.append(output_name)

    def compile_recipe(self, interactive=False):
        """Compile the Recipe into an OCEAN script and write it to the 
           current rundir."""
        if self.rundir is None:
            self.log.error("Need to specify a rundir before Recipe.compile_ocean()")
            return

        with open(os.path.join(self.full_rundir, "compiled_recipe.ocn"),'w') as write_file:
            write_file.write(self.ocn_script)
            #Append an exit statement to the output of OCEAN scripts to avoid going into 
            #interactive mode.
            if not interactive:
                write_file.write("\nexit()")
            


    def run(self, interactive=False):
        """Run the Recipe"""

        ## 1) Check that all appropriate variables are defined. ##
        if self.rundir is None:
            self.log.error("Need to specify a rundir before Recipe.run()")
            return

        if self.cdslib is None:
            self.log.error("Need to specify cds.lib file before Recipe.run()")
            return
            
        if os.system("which ocean") != 0:
            self.log.error("Cannot find 'ocean' executable on your path.")
            return
        

        OCEAN_COMMAND = ["ocean","-restore","compiled_recipe.ocn",">","simulation.log","2>&1", "-cdslib",self.cdslib]


        ## 2) Final compilation of recipe. ##
        self.compile_recipe(interactive)
        self.log.info("Running simulation...")
        
        subprocess.run(OCEAN_COMMAND, cwd=self.full_rundir)
        self.log.info("Simulation complete!")

        for a in self.analysis_tasks:
            self._txt_to_csv(a)

    def launch_viva(self):
        results_dir = self.get_results_dir()
        if results_dir is  None:
            self.log.info("Viva can only automatically open the results directory if it is defined in ocean/rhythm")
            viva_cmd = ["viva"]
        else:
            viva_cmd = ["viva", "-datadir", results_dir]
        subprocess.run(viva_cmd)

    ####################
    # Helper Functions #
    ####################

    def _txt_to_csv(self,outputname):
        """Convert raw TXT files generated by OCEAN into CSVs"""
        txt_filename = os.path.join(self.full_rundir,f"{outputname}.txt")
        csv_filename = os.path.join(self.full_rundir,f"{outputname}.csv")
        
        rows = []
        header = None

        with open(txt_filename, "r") as f:
            for line in f:
                stripped = line.strip()

                # Ignore blank lines entirely
                if not stripped:
                    continue

                # Split on exactly FOUR spaces
                parts = re.split(r'\s{4,}', line.rstrip("\n"))


                # Remaining = data rows
                rows.append(parts)

        # Write out to CSV
        with open(csv_filename, "w", newline="") as out:
            writer = csv.writer(out)
            writer.writerows(rows)

    def get_results_dir(self):
        text = self.ocn_script
        m = re.search(r'resultsDir\s*\(\s*"(.*?)"\s*\)', text)
        if m:
            return m.group(1)
        return None

    def save_results_local(self):
        self.set_results_dir(self.full_rundir)

    def set_results_dir(self, new_path):
        text = self.ocn_script
        lines = text.splitlines(keepends=True)

        # Regex to match existing resultsDir("...")
        pattern = re.compile(r'(resultsDir\s*\(\s*")(.*?)(".*\))')

        replaced = False
        updated_lines = []
        
        for line in lines:
            # If resultsDir(...) exists, replace its path
            m = pattern.search(line)
            if m and not replaced:
                line = pattern.sub(rf'\1{new_path}\3', line)
                replaced = True
                
            updated_lines.append(line)

        # If replaced, we're done
        if replaced:
            self.ocn_script = "".join(updated_lines)
            return

        # Otherwise, insert resultsDir after the first "simulator" line
        insert_line = f'resultsDir( "{new_path}" )\n'
        final = []
        inserted = False

        for line in updated_lines:
            final.append(line)
            if not inserted and line.lstrip().startswith("simulator"):
                final.append(insert_line)
                inserted = True

        self.ocn_script = "".join(final)
        return

